/*
 * LLFF Apurahavuosikello — datamalli ja oletusarvot
 *
 * Lähde: Kino_Lapinlahti_Apurahavuosikello_2026_v9.xlsx
 * Sisältää 4 välilehden tiedot yhdistettynä:
 *   1. Festivaali rahoitus (status varmistunut/haettu/haetaan/hylätty)
 *   2. Toisin nähty rahoitus
 *   3. Rahoittajat jaoteltuna (potentiaaliset)
 *   4. Hakuajat (deadline)
 */

import type { Assignable } from './assignments-shared';

export type GrantStatus = 'confirmed' | 'applied' | 'planning' | 'rejected';
// Apurahan ryhmittelyakseli. LLFF: festival/workshops/both. Hetki Company: rahoituksen
// kategoria (development/production/script/...). Org-kohtaiset arvot ks. getGrantCategoryDefs.
export type GrantProject = string;
export type GrantPriority = 'critical' | 'high' | 'medium' | 'international' | 'backup' | 'existing';

// Apurahan aliaktiviteetti — erillinen osa hakemustyöstä (hakemusteksti, budjetti, liitteet, ...).
// Käyttää Assignable-rajapintaa, jotta sitä voi delegoida ja hyväksyä samalla logiikalla kuin muita tehtäviä.
export interface GrantSubtask extends Assignable {
  id: string;
  text: string;            // esim. "Hakemusteksti", "Budjetti", "Liitteet"
  done: boolean;
  deadline?: string;       // YYYY-MM-DD
  note?: string;
  links?: string[];
}

export const DEFAULT_GRANT_SUBTASK_TEMPLATES = [
  'Hakemusteksti',
  'Budjetti',
  'Liitteet',
  'Tarkistus & lähetys',
];

export function buildDefaultGrantSubtasks(): GrantSubtask[] {
  const now = Date.now();
  return DEFAULT_GRANT_SUBTASK_TEMPLATES.map((text, i) => ({
    id: 'gs_' + now + '_' + i,
    text,
    done: false,
  }));
}

export interface Grant {
  id: string;
  year: number;              // budjettivuosi (2026 / 2027 / ...)
  funder: string;            // e.g., "Koneen Säätiö"
  grantName: string;         // e.g., "Toiminta-apuraha", "Tammikuun haku"
  amount: number;            // sovellettava EUR — 0 jos vain potentiaali
  amountText?: string;       // human readable like "5-50k €" if range or unknown
  status: GrantStatus;
  project: GrantProject;
  priority: GrantPriority;
  deadline?: string;         // ISO 'YYYY-MM-DD' if known, omit if continuous
  deadlineText?: string;     // e.g., "16.2.2026 klo 15:59", "Jatkuva", "~Kesäkuu 2026"
  decisionDate?: string;     // when decision expected (free text)
  responsibleId?: string;    // OrgTeamMember id
  subtasks?: GrantSubtask[]; // hakemuksen osat tekijöineen
  url?: string;
  notes?: string;
  deletedAt?: number;        // ms since epoch — jos asetettu, apuraha on roskakorissa
}

export interface GrantsSettings {
  yearTargets: Record<string, number>;  // '2026': 100000, '2027': 120000 jne.
  defaultYear?: number;                   // mikä vuosi näytetään ensin
}

export const DEFAULT_GRANTS_SETTINGS: GrantsSettings = {
  yearTargets: {
    '2026': 100000,
    '2027': 100000,
  },
  defaultYear: 2026,
};

// Normalize a grant loaded from Firestore — backfill year if missing
export const normalizeGrant = (g: Grant): Grant => ({
  ...g,
  year: g.year || 2026,
  deletedAt: typeof g.deletedAt === 'number' ? g.deletedAt : undefined,
});

// Normalize settings — handle migration from old single-yearTarget shape
export const normalizeGrantsSettings = (s: any): GrantsSettings => {
  if (s && typeof s.yearTargets === 'object') {
    return s as GrantsSettings;
  }
  // Migrate from old shape { yearTarget: number, year: number }
  const oldTarget = (s && s.yearTarget) || 100000;
  const oldYear = (s && s.year) || 2026;
  return {
    yearTargets: { [String(oldYear)]: oldTarget, '2027': 100000 },
    defaultYear: oldYear,
  };
};

// Get target for a specific year, with fallback
export const getYearTarget = (settings: GrantsSettings, year: number): number => {
  return settings.yearTargets[String(year)] ?? 100000;
};

export const STATUS_DEFS: Record<GrantStatus, { label: string; color: string; bg: string; icon: string; order: number }> = {
  confirmed: { label: 'Varmistunut',     color: '#22c55e', bg: 'rgba(34,197,94,.12)',  icon: '●', order: 1 },
  applied:   { label: 'Haettu',          color: '#f1b434', bg: 'rgba(241,180,52,.12)', icon: '◐', order: 2 },
  planning:  { label: 'Haetaan',         color: '#3788b2', bg: 'rgba(55,136,178,.12)', icon: '○', order: 3 },
  rejected:  { label: 'Hylätty',         color: '#ef6b6b', bg: 'rgba(239,107,107,.12)', icon: '✕', order: 4 },
};

export const PROJECT_DEFS: Record<GrantProject, { label: string; color: string; icon: string }> = {
  festival:  { label: 'Festivaali',   color: '#9b7cf6', icon: '★' },
  workshops: { label: 'Toisin nähty', color: '#f09a52', icon: '◇' },
  both:      { label: 'Molemmat',     color: '#2a8a86', icon: '◉' },
};

export const PRIORITY_DEFS: Record<GrantPriority, { label: string; color: string }> = {
  critical:      { label: 'Kriittinen',     color: '#ef6b6b' },
  high:          { label: 'Korkea',         color: '#f1b434' },
  medium:        { label: 'Keskitaso',      color: '#3788b2' },
  international: { label: 'Kansainvälinen', color: '#9b7cf6' },
  backup:        { label: 'Varavaihtoehto', color: '#94a3b8' },
  existing:      { label: 'Jo rahoittaja',  color: '#22c55e' },
};

// =============================================================================
// LLFF 2026 SEED — kaikki Excelistä saadut apurahat
// =============================================================================
export const LLFF_GRANTS_2026: Grant[] = [
  // ============ VARMISTUNUT (62 000 €) ============
  {
    id: 'g_kone_2026',
    year: 2026,
    funder: 'Koneen Säätiö',
    grantName: 'Toiminta-apuraha',
    amount: 50000,
    status: 'confirmed',
    project: 'festival',
    priority: 'critical',
    deadlineText: 'Syksy (vuosittain)',
    url: 'https://kfrtr.co/',
    notes: 'Päärahoittaja',
  },
  {
    id: 'g_hki_kehit_2026',
    year: 2026,
    funder: 'Helsingin kaupunki',
    grantName: 'Kehittämisavustus',
    amount: 12000,
    status: 'confirmed',
    project: 'festival',
    priority: 'high',
    url: 'https://avustukset.hel.fi/',
  },

  // ============ HAETTU (odottaa päätöstä) ============
  {
    id: 'g_skr_jan_2026',
    year: 2026,
    funder: 'Suomen Kulttuurirahasto',
    grantName: 'Tammikuun haku',
    amount: 36000,
    amountText: '5–50k €',
    status: 'applied',
    project: 'both',
    priority: 'high',
    deadline: '2026-02-06',
    deadlineText: '6.2.2026 klo 16',
    decisionDate: 'Huhti–touko 2026',
    url: 'https://skr.fi/',
  },
  {
    id: 'g_norden_2026',
    year: 2026,
    funder: 'Norden 0–30',
    grantName: 'Hankerahoitus / Nuorten hankkeet',
    amount: 30000,
    amountText: 'Max 50k €',
    status: 'applied',
    project: 'festival',
    priority: 'critical',
    deadline: '2026-02-16',
    deadlineText: '16.2.2026 klo 15:59',
    decisionDate: 'Kevät 2026',
    url: 'https://www.nkk.org/',
    notes: 'HAETAAN NYT — DL 16.2.2026',
  },
  {
    id: 'g_kordelin_workshops_2026',
    year: 2026,
    funder: 'Alfred Kordelinin säätiö',
    grantName: 'Suuret kulttuurihankkeet (2-vuotinen)',
    amount: 250000,
    amountText: '100–300k €',
    status: 'applied',
    project: 'workshops',
    priority: 'high',
    deadline: '2026-01-31',
    deadlineText: '31.1.2026 klo 16',
    decisionDate: 'Toukokuu 2026',
    url: 'https://kordelin.fi/',
    notes: '2-vuotinen, 125k/vuosi',
  },

  // ============ HAETAAN (suunnitteilla) ============
  {
    id: 'g_nordisk_film_tv',
    year: 2026,
    funder: 'Nordisk Film & TV Fond',
    grantName: 'Hankerahoitus',
    amount: 5000,
    status: 'planning',
    project: 'festival',
    priority: 'existing',
    deadlineText: 'Jatkuva',
    url: 'https://nordiskfilmogtvfond.com/',
  },
  {
    id: 'g_yle_2026',
    year: 2026,
    funder: 'Yle',
    grantName: 'Sponsorointi',
    amount: 5000,
    status: 'planning',
    project: 'festival',
    priority: 'medium',
    deadlineText: 'Neuvoteltava',
    url: 'https://yle.fi/',
  },

  // ============ HYLÄTTY (2026 syklin alkupuolella) ============
  {
    id: 'g_ses_fest_rejected',
    year: 2026,
    funder: 'Suomen elokuvasäätiö (SES)',
    grantName: 'Festivaalituki',
    amount: 20000,
    amountText: 'Osa 600k€/v',
    status: 'rejected',
    project: 'festival',
    priority: 'critical',
    deadlineText: '~Tammikuu 2026',
    url: 'https://www.ses.fi/',
    notes: 'Hylätty 2026 — yritetään uudestaan',
  },
  {
    id: 'g_hki_proj_rejected',
    year: 2026,
    funder: 'Helsingin kaupunki',
    grantName: 'Projektiavustus',
    amount: 20000,
    status: 'rejected',
    project: 'festival',
    priority: 'high',
    url: 'https://avustukset.hel.fi/',
  },
  {
    id: 'g_hki_toim_rejected',
    year: 2026,
    funder: 'Helsingin kaupunki',
    grantName: 'Toiminta-avustus',
    amount: 20000,
    status: 'rejected',
    project: 'festival',
    priority: 'high',
    url: 'https://avustukset.hel.fi/',
  },

  // ============ HAKUAJAT 2026 — TULEVAT HAUT (HAETAAN/SUUNNITTEILLA) ============
  {
    id: 'g_screen_brussels',
    year: 2026,
    funder: 'Screen Brussels',
    grantName: 'Yhteistuotantotuki',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'both',
    priority: 'international',
    deadline: '2026-01-17',
    deadlineText: '17.1.2026',
    url: 'https://screen.brussels/',
  },
  {
    id: 'g_whickers',
    year: 2026,
    funder: 'The Whickers Award',
    grantName: 'Dokumenttipalkinto',
    amount: 0,
    amountText: '£120 000',
    status: 'planning',
    project: 'workshops',
    priority: 'international',
    deadline: '2026-01-30',
    deadlineText: '30.1.2026',
    url: 'https://whfrankfurts.com/',
  },
  {
    id: 'g_ncp_verkosto',
    year: 2026,
    funder: 'Nordic Culture Point',
    grantName: 'Verkostoyhteistyö',
    amount: 0,
    amountText: 'Max 100k €',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadline: '2026-02-09',
    deadlineText: '9.2.2026',
    url: 'https://www.nkk.org/',
  },
  {
    id: 'g_idfa_bertha',
    year: 2026,
    funder: 'IDFA Bertha Fund',
    grantName: 'Dokumenttituki',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'workshops',
    priority: 'international',
    deadline: '2026-02-10',
    deadlineText: '10.2.2026',
    url: 'https://www.idfa.nl/',
  },
  {
    id: 'g_ncf_helmi',
    year: 2026,
    funder: 'Nordic Culture Fund',
    grantName: 'Hankerahoitus (kevät)',
    amount: 0,
    amountText: 'Max 500k DKK',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadline: '2026-02-13',
    deadlineText: '13.2.2026',
    url: 'https://nordiskkulturfond.org/',
  },
  {
    id: 'g_taike_alueet',
    year: 2026,
    funder: 'Taike',
    grantName: 'Alueiden apurahat',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'workshops',
    priority: 'medium',
    deadline: '2026-03-11',
    deadlineText: '11.3.2026',
    url: 'https://www.taike.fi/',
  },
  {
    id: 'g_skr_maalis',
    year: 2026,
    funder: 'Suomen Kulttuurirahasto',
    grantName: 'Maaliskuun haku',
    amount: 0,
    amountText: 'Kuluapuraha',
    status: 'planning',
    project: 'both',
    priority: 'medium',
    deadline: '2026-03-31',
    deadlineText: '31.3.2026 klo 16',
    url: 'https://skr.fi/',
  },
  {
    id: 'g_wihuri_2026',
    year: 2026,
    funder: 'Jenny ja Antti Wihurin rahasto',
    grantName: 'Yleinen haku',
    amount: 0,
    amountText: '5–100k+ €',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadline: '2026-05-31',
    deadlineText: '~31.5.2026',
    url: 'https://wihurinrahasto.fi/',
  },
  {
    id: 'g_torino_film_lab',
    year: 2026,
    funder: 'Torino Film Lab',
    grantName: 'Workshop + tuotantotuki',
    amount: 0,
    amountText: 'Tuotantotuki',
    status: 'planning',
    project: 'workshops',
    priority: 'international',
    deadline: '2026-06-15',
    deadlineText: '~Kesäkuu 2026',
    url: 'https://www.torinofilmlab.it/',
  },
  {
    id: 'g_kordelin_syys',
    year: 2026,
    funder: 'Alfred Kordelinin säätiö',
    grantName: 'Syyshaku',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'workshops',
    priority: 'medium',
    deadline: '2026-08-31',
    deadlineText: '31.8.2026 klo 16',
    url: 'https://kordelin.fi/',
  },
  {
    id: 'g_hki_toim_2027',
    year: 2026,
    funder: 'Helsingin kaupunki',
    grantName: 'Toiminta-avustus 2027',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'festival',
    priority: 'high',
    deadline: '2026-09-01',
    deadlineText: '~1.9.2026',
    url: 'https://avustukset.hel.fi/',
  },
  {
    id: 'g_ncf_syys',
    year: 2026,
    funder: 'Nordic Culture Fund',
    grantName: 'Syyshaku',
    amount: 0,
    amountText: 'Max 500k DKK',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadline: '2026-09-04',
    deadlineText: '~4.9.2026',
    url: 'https://nordiskkulturfond.org/',
  },
  {
    id: 'g_skr_loka',
    year: 2026,
    funder: 'Suomen Kulttuurirahasto',
    grantName: 'Lokakuun haku',
    amount: 0,
    amountText: '5–50k €',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadline: '2026-10-31',
    deadlineText: '~31.10.2026',
    url: 'https://skr.fi/',
  },
  {
    id: 'g_taike_fest',
    year: 2026,
    funder: 'Taike',
    grantName: 'Festivaaliavustukset',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'festival',
    priority: 'backup',
    deadline: '2026-11-07',
    deadlineText: '~7.11.2026',
    url: 'https://haeavustuksia.fi/',
  },
  {
    id: 'g_taike_kohde',
    year: 2026,
    funder: 'Taike',
    grantName: 'Kohdeapurahat 2027–28',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'workshops',
    priority: 'high',
    deadline: '2026-12-03',
    deadlineText: '~3.12.2026',
    url: 'https://www.taike.fi/',
  },
  {
    id: 'g_hki_proj_q1_2027',
    year: 2026,
    funder: 'Helsingin kaupunki',
    grantName: 'Projektiavustus Q1/27',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'festival',
    priority: 'high',
    deadline: '2026-12-08',
    deadlineText: '8.12.2026 klo 16',
    url: 'https://avustukset.hel.fi/',
  },

  // ============ JATKUVAT HAUT ============
  {
    id: 'g_jaes',
    year: 2026,
    funder: 'Jane ja Aatos Erkon säätiö',
    grantName: 'Suuret hankkeet',
    amount: 0,
    amountText: '50–500k+ €',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadlineText: 'Jatkuva',
    url: 'https://jaes.fi/',
  },
  {
    id: 'g_avek',
    year: 2026,
    funder: 'AVEK',
    grantName: 'AV-kulttuuri / koulutusapurahat',
    amount: 0,
    amountText: '3–55k €',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadlineText: 'Jatkuva',
    url: 'https://kopiosto.fi/AVEK/',
  },
  {
    id: 'g_creative_europe',
    year: 2026,
    funder: 'Creative Europe MEDIA',
    grantName: 'EU festivaalituki',
    amount: 0,
    amountText: '20–75k €',
    status: 'planning',
    project: 'festival',
    priority: 'international',
    deadlineText: 'Jatkuva (kevät)',
    url: 'https://ec.europa.eu/',
  },
  {
    id: 'g_eurimages',
    year: 2026,
    funder: 'Eurimages',
    grantName: 'Yhteistuotanto',
    amount: 0,
    amountText: '~27.5M€/v budj.',
    status: 'planning',
    project: 'both',
    priority: 'international',
    deadlineText: 'Jatkuva (3x/vuosi)',
    url: 'https://www.coe.int/eurimages',
  },
  {
    id: 'g_norwegian_film_inst',
    year: 2026,
    funder: 'Norwegian Film Institute',
    grantName: 'Yhteistuotanto',
    amount: 0,
    amountText: '50–300k €',
    status: 'planning',
    project: 'both',
    priority: 'international',
    deadlineText: 'Jatkuva',
    url: 'https://www.nfi.no/',
  },
  {
    id: 'g_berlinale_wcf',
    year: 2026,
    funder: 'Berlinale World Cinema Fund',
    grantName: 'Tuotantotuki',
    amount: 0,
    amountText: 'Max 60k €',
    status: 'planning',
    project: 'workshops',
    priority: 'international',
    deadlineText: 'Jatkuva (useita)',
    url: 'https://www.berlinale.de/wcf/',
  },
];

// =============================================================================
// LLFF 2027 SEED — tärkeimmät toistuvat apurahat 2026:n syklin pohjalta
// Sisältää käytännössä kaikki vuosittain toistuvat haut sekä uudet kohdat 2027:lle
// =============================================================================
export const LLFF_GRANTS_2027: Grant[] = [
  // ============ FESTIVAALIN PÄÄRAHOITUS — TOISTUVAT 2026 STA ============
  {
    id: 'g_kone_2027',
    year: 2027,
    funder: 'Koneen Säätiö',
    grantName: 'Toiminta-apuraha 2027',
    amount: 50000,
    status: 'planning',
    project: 'festival',
    priority: 'critical',
    deadline: '2027-09-15',
    deadlineText: '~Syksy 2027',
    url: 'https://kfrtr.co/',
    notes: 'Päärahoittaja — vuosittainen jatko 2026 myönnetylle',
  },
  {
    id: 'g_ses_fest_2027',
    year: 2027,
    funder: 'Suomen elokuvasäätiö (SES)',
    grantName: 'Festivaalituki — uusi yritys',
    amount: 25000,
    amountText: 'Osa 600k€/v',
    status: 'planning',
    project: 'festival',
    priority: 'critical',
    deadline: '2027-01-15',
    deadlineText: '~Tammikuu 2027',
    url: 'https://www.ses.fi/',
    notes: '2026 hylätty — vahvistettava hakemus 2027:lle',
  },
  {
    id: 'g_hki_kehit_2027',
    year: 2027,
    funder: 'Helsingin kaupunki',
    grantName: 'Kehittämisavustus 2027',
    amount: 12000,
    status: 'planning',
    project: 'festival',
    priority: 'high',
    deadlineText: '~Tammikuu 2027',
    url: 'https://avustukset.hel.fi/',
    notes: '2026 myönnetty — uusi haku 2027:lle',
  },
  {
    id: 'g_hki_toim_2028',
    year: 2027,
    funder: 'Helsingin kaupunki',
    grantName: 'Toiminta-avustus 2028',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'festival',
    priority: 'high',
    deadline: '2027-09-01',
    deadlineText: '~1.9.2027',
    url: 'https://avustukset.hel.fi/',
  },
  {
    id: 'g_hki_proj_q1_2028',
    year: 2027,
    funder: 'Helsingin kaupunki',
    grantName: 'Projektiavustus Q1/2028',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'festival',
    priority: 'high',
    deadline: '2027-12-08',
    deadlineText: '~8.12.2027 klo 16',
    url: 'https://avustukset.hel.fi/',
  },

  // ============ SUOMEN KULTTUURIRAHASTO — KAIKKI 3 VUOSITTAISTA HAKUA ============
  {
    id: 'g_skr_jan_2027',
    year: 2027,
    funder: 'Suomen Kulttuurirahasto',
    grantName: 'Tammikuun haku',
    amount: 36000,
    amountText: '5–50k €',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadline: '2027-02-06',
    deadlineText: '~6.2.2027 klo 16',
    decisionDate: 'Huhti–touko 2027',
    url: 'https://skr.fi/',
  },
  {
    id: 'g_skr_maalis_2027',
    year: 2027,
    funder: 'Suomen Kulttuurirahasto',
    grantName: 'Maaliskuun haku',
    amount: 0,
    amountText: 'Kuluapuraha',
    status: 'planning',
    project: 'both',
    priority: 'medium',
    deadline: '2027-03-31',
    deadlineText: '~31.3.2027 klo 16',
    url: 'https://skr.fi/',
  },
  {
    id: 'g_skr_loka_2027',
    year: 2027,
    funder: 'Suomen Kulttuurirahasto',
    grantName: 'Lokakuun haku',
    amount: 0,
    amountText: '5–50k €',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadline: '2027-10-31',
    deadlineText: '~31.10.2027',
    url: 'https://skr.fi/',
  },

  // ============ POHJOISMAINEN — VUOSITTAISET ============
  {
    id: 'g_norden_2027',
    year: 2027,
    funder: 'Norden 0–30',
    grantName: 'Hankerahoitus / Nuorten hankkeet',
    amount: 30000,
    amountText: 'Max 50k €',
    status: 'planning',
    project: 'festival',
    priority: 'critical',
    deadline: '2027-02-16',
    deadlineText: '~16.2.2027 klo 15:59',
    decisionDate: 'Kevät 2027',
    url: 'https://www.nkk.org/',
  },
  {
    id: 'g_ncf_helmi_2027',
    year: 2027,
    funder: 'Nordic Culture Fund',
    grantName: 'Hankerahoitus (kevät)',
    amount: 0,
    amountText: 'Max 500k DKK',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadline: '2027-02-13',
    deadlineText: '~13.2.2027',
    url: 'https://nordiskkulturfond.org/',
  },
  {
    id: 'g_ncf_syys_2027',
    year: 2027,
    funder: 'Nordic Culture Fund',
    grantName: 'Syyshaku',
    amount: 0,
    amountText: 'Max 500k DKK',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadline: '2027-09-04',
    deadlineText: '~4.9.2027',
    url: 'https://nordiskkulturfond.org/',
  },
  {
    id: 'g_ncp_verkosto_2027',
    year: 2027,
    funder: 'Nordic Culture Point',
    grantName: 'Verkostoyhteistyö',
    amount: 0,
    amountText: 'Max 100k €',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadline: '2027-02-09',
    deadlineText: '~9.2.2027',
    url: 'https://www.nkk.org/',
  },

  // ============ KORDELIN — TOISIN NÄHTY JATKUU ============
  {
    id: 'g_kordelin_workshops_2027',
    year: 2027,
    funder: 'Alfred Kordelinin säätiö',
    grantName: 'Suuret kulttuurihankkeet (vuoden 2 osuus)',
    amount: 125000,
    amountText: '125k/vuosi',
    status: 'planning',
    project: 'workshops',
    priority: 'critical',
    deadlineText: '2-vuotinen jatko (jos 2026 myönnettiin)',
    url: 'https://kordelin.fi/',
    notes: 'Riippuu 2026 hyväksynnästä — Toisin nähty hankkeen 2. vuosi',
  },
  {
    id: 'g_kordelin_jan_2027',
    year: 2027,
    funder: 'Alfred Kordelinin säätiö',
    grantName: 'Suuret kulttuurihankkeet (uusi haku)',
    amount: 0,
    amountText: '100–300k €',
    status: 'planning',
    project: 'workshops',
    priority: 'high',
    deadline: '2027-01-31',
    deadlineText: '~31.1.2027 klo 16',
    decisionDate: 'Toukokuu 2027',
    url: 'https://kordelin.fi/',
  },
  {
    id: 'g_kordelin_syys_2027',
    year: 2027,
    funder: 'Alfred Kordelinin säätiö',
    grantName: 'Syyshaku',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'workshops',
    priority: 'medium',
    deadline: '2027-08-31',
    deadlineText: '~31.8.2027 klo 16',
    url: 'https://kordelin.fi/',
  },

  // ============ TAIKE — VUOSITTAISET ============
  {
    id: 'g_taike_fest_2027',
    year: 2027,
    funder: 'Taike',
    grantName: 'Festivaaliavustukset',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'festival',
    priority: 'backup',
    deadline: '2027-11-07',
    deadlineText: '~7.11.2027',
    url: 'https://haeavustuksia.fi/',
  },
  {
    id: 'g_taike_kohde_2027',
    year: 2027,
    funder: 'Taike',
    grantName: 'Kohdeapurahat 2028–29',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'workshops',
    priority: 'high',
    deadline: '2027-12-03',
    deadlineText: '~3.12.2027',
    url: 'https://www.taike.fi/',
  },

  // ============ WIHURI — VUOSITTAINEN ============
  {
    id: 'g_wihuri_2027',
    year: 2027,
    funder: 'Jenny ja Antti Wihurin rahasto',
    grantName: 'Yleinen haku',
    amount: 0,
    amountText: '5–100k+ €',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadline: '2027-05-31',
    deadlineText: '~31.5.2027',
    url: 'https://wihurinrahasto.fi/',
  },

  // ============ KANSAINVÄLISET — VUOSITTAISET ============
  {
    id: 'g_whickers_2027',
    year: 2027,
    funder: 'The Whickers Award',
    grantName: 'Dokumenttipalkinto',
    amount: 0,
    amountText: '£120 000',
    status: 'planning',
    project: 'workshops',
    priority: 'international',
    deadline: '2027-01-30',
    deadlineText: '~30.1.2027',
    url: 'https://whfrankfurts.com/',
  },
  {
    id: 'g_idfa_bertha_2027',
    year: 2027,
    funder: 'IDFA Bertha Fund',
    grantName: 'Dokumenttituki',
    amount: 0,
    amountText: 'Vaihtelee',
    status: 'planning',
    project: 'workshops',
    priority: 'international',
    deadline: '2027-02-10',
    deadlineText: '~10.2.2027',
    url: 'https://www.idfa.nl/',
  },
  {
    id: 'g_torino_2027',
    year: 2027,
    funder: 'Torino Film Lab',
    grantName: 'Workshop + tuotantotuki',
    amount: 0,
    amountText: 'Tuotantotuki',
    status: 'planning',
    project: 'workshops',
    priority: 'international',
    deadline: '2027-06-15',
    deadlineText: '~Kesäkuu 2027',
    url: 'https://www.torinofilmlab.it/',
  },
  {
    id: 'g_creative_europe_2027',
    year: 2027,
    funder: 'Creative Europe MEDIA',
    grantName: 'EU festivaalituki',
    amount: 0,
    amountText: '20–75k €',
    status: 'planning',
    project: 'festival',
    priority: 'international',
    deadline: '2027-04-01',
    deadlineText: '~Kevät 2027',
    url: 'https://ec.europa.eu/',
  },

  // ============ JATKUVAT (vuosittain mahdollista hakea) ============
  {
    id: 'g_jaes_2027',
    year: 2027,
    funder: 'Jane ja Aatos Erkon säätiö',
    grantName: 'Suuret hankkeet',
    amount: 0,
    amountText: '50–500k+ €',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadlineText: 'Jatkuva',
    url: 'https://jaes.fi/',
  },
  {
    id: 'g_avek_2027',
    year: 2027,
    funder: 'AVEK',
    grantName: 'AV-kulttuuri / koulutusapurahat',
    amount: 0,
    amountText: '3–55k €',
    status: 'planning',
    project: 'both',
    priority: 'high',
    deadlineText: 'Jatkuva',
    url: 'https://kopiosto.fi/AVEK/',
  },
];

// Yhdistetty seed-data (default Firestoreen)
export const LLFF_GRANTS_DEFAULT: Grant[] = [...LLFF_GRANTS_2026, ...LLFF_GRANTS_2027];

// Helper: parse "YYYY-MM-DD" → Date safely
export const parseGrantDeadline = (s?: string): Date | null => {
  if (!s) return null;
  const [y, m, d] = s.split('-').map(n => parseInt(n, 10));
  if (!y || !m || !d) return null;
  return new Date(y, m - 1, d);
};

// Days from now to deadline (negative = passed)
export const daysUntilDeadline = (g: Grant): number | null => {
  const d = parseGrantDeadline(g.deadline);
  if (!d) return null;
  return Math.ceil((d.getTime() - Date.now()) / 86400000);
};

// Counts grants in each status
export const getStatusTotals = (grants: Grant[]) => {
  const totals = {
    confirmed: 0,
    applied: 0,
    planning: 0,
    rejected: 0,
  };
  grants.forEach(g => {
    totals[g.status] += g.amount || 0;
  });
  return totals;
};


// =============================================================================
// HETKI COMPANY — Rahoitusvuosikello (tuotantoyhtiön rahoittajarekisteri)
//
// Lähde: Rahoittajat_apurahat_2026.xlsx (58 rahoittajaa: FI / NO / EU / KV).
// Ryhmittely 'project'-kentällä = rahoituksen KATEGORIA (ks. HETKI_CATEGORY_DEFS).
// Kaikki status 'planning' (Ei haettu) ja amount 0 — summat kentässä amountText,
// koska mitään ei vielä myönnetty. priority: Suomi='high', muut='international'.
// =============================================================================

export interface ProjectDef { label: string; color: string; icon: string; }

// Hetki Companyn kategoriat (korvaa LLFF:n festival/workshops/both-akselin)
export const HETKI_CATEGORY_DEFS: Record<string, ProjectDef> = {
  development:  { label: 'Kehittäminen',          color: '#3788b2', icon: '◈' },
  production:   { label: 'Tuotantotuki',          color: '#9b7cf6', icon: '★' },
  script:       { label: 'Käsikirjoitus',         color: '#f09a52', icon: '✎' },
  personal:     { label: 'Henkilökoht. apuraha',  color: '#2a8a86', icon: '●' },
  social:       { label: 'Yhteiskunnallinen',     color: '#ef6b6b', icon: '◆' },
  innovation:   { label: 'Innovaatio',            color: '#f1b434', icon: '✦' },
  distribution: { label: 'Levitys / pitching',    color: '#94a3b8', icon: '▷' },
};

export const HETKI_CATEGORY_ORDER: string[] = [
  'development', 'production', 'script', 'personal', 'social', 'innovation', 'distribution',
];

const LLFF_PROJECT_ORDER: string[] = ['festival', 'workshops', 'both'];

// Org-kohtainen ryhmittelyakseli apurahanäkymälle.
export function getGrantCategoryDefs(orgSlug: string): Record<string, ProjectDef> {
  return orgSlug === 'hetki-company' ? HETKI_CATEGORY_DEFS : PROJECT_DEFS;
}
export function getGrantCategoryOrder(orgSlug: string): string[] {
  return orgSlug === 'hetki-company' ? HETKI_CATEGORY_ORDER : LLFF_PROJECT_ORDER;
}
export function getGrantCategoryLabel(orgSlug: string): string {
  return orgSlug === 'hetki-company' ? 'Kategoria' : 'Hanke';
}

export const HETKI_GRANTS_2026: Grant[] = [
  {
    id: 'g_hetki_fi01',
    year: 2026,
    funder: 'SES',
    grantName: 'Kehittämistuki',
    amount: 0,
    amountText: '10–80 k€',
    status: 'planning',
    project: 'development',
    priority: 'high',
    deadline: '2026-04-01',
    deadlineText: '1.4.2026 klo 16:00 (myös 6.8. ja 7.10.2026)',
    decisionDate: '12.6.2026',
    url: 'https://www.ses.fi/en/funding/deadlines/',
    notes: 'Pääväylä kotimaiseen kehitysrahoitukseen. Tee kontakti ennen hakua.\nKelpoisuus: Suomalainen tuotantoyhtiö (Y-tunnus). Ammattimainen toiminta.\nHakukierrokset: 3 kierrosta/vuosi\nPäätös: 12.6.2026\nVaatimukset: Kehittämissuunnitelma, budjetti, treatment, ohjaajan visio\nLiitteet: Synopsis, treatment, budjetti, rahoitussuunnitelma, CV:t, yhtiön tilinpäätös\nYhteys: tukineuvonta@ses.fi',
  },
  {
    id: 'g_hetki_fi02',
    year: 2026,
    funder: 'SES',
    grantName: 'Tuotantotuki',
    amount: 0,
    amountText: '200 k€ – 1,5 M€',
    status: 'planning',
    project: 'production',
    priority: 'high',
    deadline: '2026-04-01',
    deadlineText: '1.4.2026 klo 16:00',
    decisionDate: '12.6.2026',
    url: 'https://www.ses.fi/en/funding/',
    notes: 'Vaatii käytännössä broadcaster- tai levityssitoumuksen.\nKelpoisuus: Suomalainen tuotantoyhtiö, kehittäminen valmis, rahoituspaketti kasassa ≥ 70 %\nHakukierrokset: 3 kierrosta/vuosi (1.4. / 6.8. / 7.10.2026)\nPäätös: 12.6.2026\nVaatimukset: Valmis käsikirjoitus, rahoitussuunnitelma, levityssopimukset\nLiitteet: Lopullinen käsikirjoitus, tuotantosuunnitelma, budjetti, rahoituspaketti, levityssitoumukset\nYhteys: tukineuvonta@ses.fi',
  },
  {
    id: 'g_hetki_fi03',
    year: 2026,
    funder: 'SES',
    grantName: 'Slate-kehittämistuki',
    amount: 0,
    amountText: '150–300 k€',
    status: 'planning',
    project: 'development',
    priority: 'high',
    deadline: '2026-04-01',
    deadlineText: '1.4.2026',
    decisionDate: '12.6.2026',
    url: 'https://www.ses.fi/en/funding/support-guides/slate-development-support/',
    notes: 'Sopiva keskikokoiselle yhtiölle, jolla useita projekteja samaan aikaan.\nKelpoisuus: Tuotantoyhtiö, 3–5 projektin slate, näyttöä aiemmasta toiminnasta\nHakukierrokset: 1 kierros/vuosi\nPäätös: 12.6.2026\nVaatimukset: Slate-strategia, 3–5 projektin synopsikset, yhtiön strategia\nLiitteet: Slate-suunnitelma, projektien treatmentit, budjetti, CV:t, yhtiön talous\nYhteys: tukineuvonta@ses.fi',
  },
  {
    id: 'g_hetki_fi04',
    year: 2026,
    funder: 'SES',
    grantName: 'Lyhytelokuvatuki',
    amount: 0,
    amountText: '20–60 k€',
    status: 'planning',
    project: 'production',
    priority: 'high',
    deadline: '2026-04-01',
    deadlineText: '1.4.2026',
    decisionDate: '12.6.2026',
    url: 'https://www.ses.fi/en/funding/',
    notes: 'Lyhytelokuviin myös erilliset SES-haut keväällä ja syksyllä.\nKelpoisuus: Tuotantoyhtiö tai työryhmä\nHakukierrokset: 3 kierrosta/vuosi\nPäätös: 12.6.2026\nVaatimukset: Käsikirjoitus, ohjaajan visio, budjetti\nLiitteet: Käsikirjoitus, treatment, budjetti, rahoitussuunnitelma\nYhteys: tukineuvonta@ses.fi',
  },
  {
    id: 'g_hetki_fi05',
    year: 2026,
    funder: 'AVEK',
    grantName: 'Käsikirjoitustuki (henkilökohtainen)',
    amount: 0,
    amountText: '3–12 k€',
    status: 'planning',
    project: 'script',
    priority: 'high',
    deadlineText: 'Jatkuva (rolling)',
    decisionDate: 'n. 4–6 vk',
    url: 'https://kopiosto.fi/en/AVEK/funding/',
    notes: 'Nopea reagointi, hyvä alkuvaiheen rahoitus.\nKelpoisuus: Yksityishenkilö, käsikirjoittaja\nHakukierrokset: Jatkuva haku, päätökset n. kerran kk\nPäätös: n. 4–6 vk\nVaatimukset: Käsikirjoitus tai treatment, työsuunnitelma, CV\nLiitteet: Käsikirjoitusote, synopsis, työsuunnitelma, budjetti, CV\nYhteys: avek@kopiosto.fi',
  },
  {
    id: 'g_hetki_fi06',
    year: 2026,
    funder: 'AVEK',
    grantName: 'Tuotantotuki (yritys)',
    amount: 0,
    amountText: '10–80 k€',
    status: 'planning',
    project: 'production',
    priority: 'high',
    deadlineText: 'Jatkuva (rolling)',
    decisionDate: 'n. 4–6 vk',
    url: 'https://kopiosto.fi/en/AVEK/funding/',
    notes: 'Tuet vähentyneet 2025–26. Toinen reitti: AVEK + SES yhdessä.\nKelpoisuus: Suomalainen tuotantoyhtiö\nHakukierrokset: Jatkuva haku (huom. 2026 tauotuksia – tarkista)\nPäätös: n. 4–6 vk\nVaatimukset: Tuotantosuunnitelma, budjetti, käsikirjoitus\nLiitteet: Käsikirjoitus, budjetti, rahoitussuunnitelma, työryhmä, yhtiön tiedot\nYhteys: avek@kopiosto.fi',
  },
  {
    id: 'g_hetki_fi07',
    year: 2026,
    funder: 'AVEK',
    grantName: 'Kehittämö (Talent Development Lab)',
    amount: 0,
    amountText: 'Stipendi 6–8 k€ + ohjelma',
    status: 'planning',
    project: 'development',
    priority: 'high',
    deadline: '2026-11-27',
    deadlineText: '~27.11.2026 klo 16 (aikataulu tarkentuu)',
    decisionDate: 'Talvi 2026/27',
    url: 'https://kopiosto.fi/en/AVEK/funding/avek-grants-and-support-guidelines/kehittamo-talent-development-lab/',
    notes: 'Erinomainen uraa rakentavalle tekijälle.\nKelpoisuus: Lupaavat käsikirjoittajat ja ohjaajat (alle 5 v. uralta)\nHakukierrokset: 1 kierros/vuosi\nPäätös: Talvi 2026/27\nVaatimukset: Konsepti, CV, motivaatio\nLiitteet: Hakemus, CV, näyte aiemmasta työstä\nYhteys: avek@kopiosto.fi',
  },
  {
    id: 'g_hetki_fi08',
    year: 2026,
    funder: 'Taike',
    grantName: 'Taiteilija-apurahat',
    amount: 0,
    amountText: '6 / 12 kk työskentely (n. 2 600 €/kk)',
    status: 'planning',
    project: 'personal',
    priority: 'high',
    deadline: '2026-04-01',
    deadlineText: '2.3.–1.4.2026 klo 16:00',
    decisionDate: '30.6.2026',
    url: 'https://www.taike.fi/en/calls-for-applications/call-applications-2026-artist-grants',
    notes: 'Taike + KAVI yhdistyivät 1.1.2026. Hakuportaali: applyforgrants.fi\nKelpoisuus: Ammattitaiteilija (audiovisuaalinen taide, mediataide)\nHakukierrokset: 1 kierros/vuosi\nPäätös: 30.6.2026\nVaatimukset: Taiteellinen ansioluettelo, työsuunnitelma\nLiitteet: Työsuunnitelma, CV, näytteet, talousarvio\nYhteys: asiakaspalvelu@taike.fi',
  },
  {
    id: 'g_hetki_fi09',
    year: 2026,
    funder: 'Taike',
    grantName: 'Kohdeapuraha (projekti)',
    amount: 0,
    amountText: '5–25 k€',
    status: 'planning',
    project: 'production',
    priority: 'high',
    deadline: '2026-04-01',
    deadlineText: '1.4.2026 (haku 2.3.-1.4.2026)',
    decisionDate: 'n. 3–4 kk',
    url: 'https://www.taike.fi/en/',
    notes: 'Voi hakea yksittäisiä projekteja kohdennetusti.\nKelpoisuus: Yksityishenkilö, työryhmä tai yhteisö\nHakukierrokset: Useita kierroksia/vuosi\nPäätös: n. 3–4 kk\nVaatimukset: Projektisuunnitelma, budjetti, taiteellinen perustelu\nLiitteet: Projektisuunnitelma, budjetti, rahoitussuunnitelma, CV\nYhteys: asiakaspalvelu@taike.fi',
  },
  {
    id: 'g_hetki_fi10',
    year: 2026,
    funder: 'Business Finland',
    grantName: 'AV Production Incentive (Cash Rebate)',
    amount: 0,
    amountText: '25 % (kansallinen) + alueellinen lisä, yhteensä jopa 40 %',
    status: 'planning',
    project: 'production',
    priority: 'high',
    deadlineText: 'Jatkuva (rolling)',
    decisionDate: 'n. 8–10 vk päätös',
    url: 'https://www.businessfinland.fi/en/services/funding/funding-services/cash-rebate/',
    notes: 'Ei summarajaa, mutta budjettikatto. Pilotointi 2026 ulk. omistajuuden osalta.\nKelpoisuus: Suomalainen tuotantoyhtiö / suomalainen yht.tuottaja. Vaatii ≥ 25 % ulkomaista yks. rahoitusta.\nHakukierrokset: Jatkuva (budjettikatto vuosittain)\nPäätös: n. 8–10 vk päätös\nVaatimukset: Ulkomaalainen yhteistuotanto / rahoitus, kustannukset Suomessa\nLiitteet: Budjetti, rahoitussopimukset, kustannusarvio Suomeen, työllistämissuunnitelma\nYhteys: av@businessfinland.fi',
  },
  {
    id: 'g_hetki_fi11',
    year: 2026,
    funder: 'Business Finland',
    grantName: 'Creative Industries R&D',
    amount: 0,
    amountText: 'Tutkimukseen/kehitykseen 50–100 k€+',
    status: 'planning',
    project: 'innovation',
    priority: 'high',
    deadline: '2026-04-29',
    deadlineText: '29.4.2026',
    decisionDate: 'n. 8 vk',
    url: 'https://www.businessfinland.fi/en/services/funding/funding-services/research-and-development-funding/Funding-to-promote-research-and-development-in-the-creative-industries/',
    notes: 'Sopii formaattien ja teknologian (esim. XR, AI) yhdistelyyn.\nKelpoisuus: Yritys, jolla T&K-hanke. Soveltuu mm. tarinankerronnan tekn. kehitykseen.\nHakukierrokset: Jatkuva haku\nPäätös: n. 8 vk\nVaatimukset: T&K-suunnitelma, liiketoimintamalli, vaikuttavuus\nLiitteet: Hankesuunnitelma, talous, IP-strategia, kasvuhalu\nYhteys: info@businessfinland.fi',
  },
  {
    id: 'g_hetki_fi12',
    year: 2026,
    funder: 'Yle',
    grantName: 'Yhteistuotanto / Ennakko-osto',
    amount: 0,
    amountText: 'Vaihtelee — kohdekohtainen',
    status: 'planning',
    project: 'production',
    priority: 'high',
    deadlineText: 'Jatkuva (rolling)',
    decisionDate: 'vaihtelee',
    url: 'https://yle.fi/aihe/yleisradio/tuotantoyhtioille',
    notes: 'Käytännössä edellytys SES-tuotantotuelle. Lähesty oman lajin tilaajaa suoraan.\nKelpoisuus: Suomalainen tuotantoyhtiö, joka tarjoaa Ylelle ohjelmaa\nHakukierrokset: Jatkuva (tarjouspyynnöt + omat tarjoukset)\nPäätös: vaihtelee\nVaatimukset: Tarjous + tuotantosuunnitelma; Ylen kanavastrategiaan sopiva\nLiitteet: Treatment, käsikirjoitus, budjetti, rahoitussuunnitelma, esittelyvideo\nYhteys: tuotantoyhtioille@yle.fi',
  },
  {
    id: 'g_hetki_fi13',
    year: 2026,
    funder: 'ELY-keskus',
    grantName: 'Alueellinen yritystuki',
    amount: 0,
    amountText: 'Tapauskohtainen',
    status: 'planning',
    project: 'development',
    priority: 'high',
    deadlineText: 'Jatkuva (rolling)',
    decisionDate: 'n. 2–3 kk',
    url: 'https://www.ely-keskus.fi/',
    notes: 'Soveltuu vain yritystoiminnan kehittämiseen, ei taiteelliseen sisältöön.\nKelpoisuus: Pk-yritys; alueelliset ehdot vaihtelevat\nHakukierrokset: Jatkuva\nPäätös: n. 2–3 kk\nVaatimukset: Yritystoiminnan kehittämishanke\nLiitteet: Hankesuunnitelma, talous, vaikuttavuus\nYhteys: Oma ELY-keskus',
  },
  {
    id: 'g_hetki_fi14',
    year: 2026,
    funder: 'Koneen Säätiö',
    grantName: 'Apuraha',
    amount: 0,
    amountText: '10–200 k€ (rohkeat avaukset)',
    status: 'planning',
    project: 'personal',
    priority: 'high',
    deadline: '2026-09-15',
    deadlineText: '1.–15.9.2026',
    decisionDate: 'Joulukuu 2026',
    url: 'https://koneensaatio.fi/en/grants/',
    notes: 'Suosii kokeellisia, taiteellisesti rohkeita projekteja. Yht.k.viestinnälle hyvä.\nKelpoisuus: Yksityishenkilö, työryhmä tai yhteisö (Suomi-yhteys)\nHakukierrokset: 1 kierros/vuosi\nPäätös: Joulukuu 2026\nVaatimukset: Rohkea ja merkityksellinen taiteellinen/tutkimuksellinen avaus, vapaa tutkimus, yhteiskunnallisuus\nLiitteet: Suunnitelma, budjetti, CV, vertaisarvioitavissa oleva työnäyte\nYhteys: saatio@koneensaatio.fi',
  },
  {
    id: 'g_hetki_fi15',
    year: 2026,
    funder: 'Suomen Kulttuurirahasto',
    grantName: 'Keskusrahasto',
    amount: 0,
    amountText: 'Työskentely 6 kk / 12 kk; projektit 5–50 k€',
    status: 'planning',
    project: 'personal',
    priority: 'high',
    deadline: '2026-10-30',
    deadlineText: '15.–30.10.2026',
    decisionDate: 'Helmikuu 2027',
    url: 'https://skr.fi/en/grants/',
    notes: 'Suuri uudistus: yhden hakukierroksen järjestelmä lokakuusta 2026 alkaen.\nKelpoisuus: Yksityishenkilö, työryhmä tai yhteisö\nHakukierrokset: 1 kierros/vuosi (2026 alkaen)\nPäätös: Helmikuu 2027\nVaatimukset: Taiteellinen tai tieteellinen ansio; selkeä suunnitelma\nLiitteet: Työsuunnitelma, budjetti, CV, suositukset, työnäytteet\nYhteys: skr@skr.fi',
  },
  {
    id: 'g_hetki_fi16',
    year: 2026,
    funder: 'SKR',
    grantName: 'Maakuntarahastot',
    amount: 0,
    amountText: '5–30 k€',
    status: 'planning',
    project: 'personal',
    priority: 'high',
    deadline: '2026-02-06',
    deadlineText: '21.1.–6.2.2026',
    decisionDate: 'Toukokuu 2026',
    url: 'https://skr.fi/en/news/regional-fund-application-round-from-21-january-to-6-february-2026/',
    notes: 'Hae siitä maakunnasta, jossa asut tai jossa työ tehdään.\nKelpoisuus: Yksityishenkilö tai työryhmä, yhteys ko. maakuntaan\nHakukierrokset: 1 kierros/vuosi\nPäätös: Toukokuu 2026\nVaatimukset: Maakunnallinen yhteys, taiteellinen perustelu\nLiitteet: Työsuunnitelma, budjetti, CV, työnäytteet\nYhteys: skr@skr.fi',
  },
  {
    id: 'g_hetki_fi17',
    year: 2026,
    funder: 'Jenny ja Antti Wihurin Rahasto',
    grantName: 'Yleinen apuraha',
    amount: 0,
    amountText: '6 / 12 kk työskentely tai 10–80 k€',
    status: 'planning',
    project: 'personal',
    priority: 'high',
    deadline: '2026-05-31',
    deadlineText: '9.–31.5.2026',
    decisionDate: 'Lokakuu 2026',
    url: 'https://wihurinrahasto.fi/en/general-grant-call/',
    notes: 'Suosii ammatillisesti vakiintuneita hakijoita; merkittäviä summia.\nKelpoisuus: Yksityishenkilö, työryhmä tai yhteisö, suomalainen yhteys\nHakukierrokset: 1 kierros/vuosi\nPäätös: Lokakuu 2026\nVaatimukset: Suomalaisen tieteen, taiteen tai yhteiskunnan edistäminen\nLiitteet: Hakemus, suunnitelma, CV, työnäytteet, suositukset\nYhteys: wihurinrahasto@wihurinrahasto.fi',
  },
  {
    id: 'g_hetki_fi18',
    year: 2026,
    funder: 'Alfred Kordelinin Säätiö',
    grantName: 'Yleiset apurahat',
    amount: 0,
    amountText: '6/12 kk työskentely tai projekti',
    status: 'planning',
    project: 'personal',
    priority: 'high',
    deadline: '2026-08-31',
    deadlineText: '31.8.2026 klo 16',
    decisionDate: 'Joulukuu 2026',
    url: 'https://kordelin.fi/en/grants/',
    notes: 'Soveltuu myös käsikirjoitustyöskentelyyn.\nKelpoisuus: Yksityishenkilö tai työryhmä\nHakukierrokset: 1 kierros/vuosi\nPäätös: Joulukuu 2026\nVaatimukset: Suomalaisen tieteen, kirjallisuuden ja taiteen edistäminen\nLiitteet: Hakemus, työsuunnitelma, CV, työnäytteet\nYhteys: info@kordelin.fi',
  },
  {
    id: 'g_hetki_fi19',
    year: 2026,
    funder: 'Alfred Kordelinin Säätiö',
    grantName: 'Suuret kulttuurihankkeet',
    amount: 0,
    amountText: '150–300 k€',
    status: 'planning',
    project: 'production',
    priority: 'high',
    deadline: '2026-01-31',
    deadlineText: '31.1.2026 klo 16',
    decisionDate: 'Maaliskuu 2026 (edell.kierros)',
    url: 'https://kordelin.fi/apurahat/suuret-kulttuurihankkeet',
    notes: 'Sopiva impact-tuotannoille tai pitkille dokumenttihankkeille.\nKelpoisuus: Yhteisö/organisaatio, merkittävä yhteiskunnallinen vaikuttavuus\nHakukierrokset: 1 kierros/vuosi\nPäätös: Maaliskuu 2026 (edell.kierros)\nVaatimukset: Mittakaavainen kulttuurihanke, vaikuttavuussuunnitelma\nLiitteet: Hankesuunnitelma, budjetti, kumppanit, vaikuttavuusmittarit\nYhteys: info@kordelin.fi',
  },
  {
    id: 'g_hetki_fi20',
    year: 2026,
    funder: 'C.V. Åkerlundin Säätiö',
    grantName: 'Apuraha',
    amount: 0,
    amountText: '3–15 k€',
    status: 'planning',
    project: 'personal',
    priority: 'high',
    deadline: '2026-08-31',
    deadlineText: '~31.8.2026 syksyn haku (aikataulu tarkentuu)',
    decisionDate: 'Joulukuu 2026',
    url: 'https://www.cvakerlund.fi/',
    notes: 'Pienempi mutta täsmälleen av-alalle suunnattu rahasto.\nKelpoisuus: Yksityishenkilö tai työryhmä av-alalla\nHakukierrokset: 1 kierros/vuosi\nPäätös: Joulukuu 2026\nVaatimukset: Audiovisuaalinen alaa edistävä työ\nLiitteet: Hakemus, suunnitelma, budjetti, CV, työnäyte\nYhteys: Tarkista säätiön sivu',
  },
  {
    id: 'g_hetki_fi21',
    year: 2026,
    funder: 'Niilo Helanderin Säätiö',
    grantName: 'Apuraha',
    amount: 0,
    amountText: '5–15 k€',
    status: 'planning',
    project: 'personal',
    priority: 'high',
    deadline: '2026-02-28',
    deadlineText: '28.2.2026 klo 23.59',
    decisionDate: 'Talvi 2026/27',
    url: 'https://niilohelander.fi/',
    notes: 'Kelpoisuus: Suomalainen taiteilija/tutkija\nHakukierrokset: 1 kierros/vuosi\nPäätös: Talvi 2026/27\nVaatimukset: Suomalaisen tieteen ja taiteen edistäminen\nLiitteet: Hakemus, suunnitelma, budjetti, CV\nYhteys: info@niilohelander.fi',
  },
  {
    id: 'g_hetki_fi22',
    year: 2026,
    funder: 'WSOY:n Kirjallisuussäätiö',
    grantName: 'Kirjallisuusapuraha',
    amount: 0,
    amountText: 'Työskentely 3–12 k€',
    status: 'planning',
    project: 'script',
    priority: 'high',
    deadline: '2026-02-28',
    deadlineText: '28.2.2026 klo 23.59',
    decisionDate: 'Kevät 2026',
    url: 'https://www.wsoy.fi/',
    notes: 'Soveltuu mm. käsikirjoitustyöhön.\nKelpoisuus: Kirjallisuuden / dramaturgian ammattilaiset\nHakukierrokset: 1 kierros/vuosi\nPäätös: Kevät 2026\nVaatimukset: Kirjallinen / dramaturginen työ\nLiitteet: Työsuunnitelma, näyte, CV, suositukset\nYhteys: info@wsoy.fi',
  },
  {
    id: 'g_hetki_fi23',
    year: 2026,
    funder: 'Otavan Kirjasäätiö',
    grantName: 'Kirjallisuusapuraha',
    amount: 0,
    amountText: 'Työskentely 3–8 k€',
    status: 'planning',
    project: 'script',
    priority: 'high',
    deadline: '2026-02-28',
    deadlineText: '28.2.2026 klo 23.59',
    decisionDate: 'vaihtelee',
    url: 'https://www.otava.fi/yritys/otavan-kirjasaatio/',
    notes: 'Kelpoisuus: Kirjallisuuden ammattilaiset\nHakukierrokset: 1 kierros/vuosi\nPäätös: vaihtelee\nVaatimukset: Kirjallinen työ\nLiitteet: Suunnitelma, näyte, CV\nYhteys: Tarkista säätiön sivu',
  },
  {
    id: 'g_hetki_fi24',
    year: 2026,
    funder: 'Paulon Säätiö',
    grantName: 'Apuraha',
    amount: 0,
    amountText: '5–20 k€',
    status: 'planning',
    project: 'personal',
    priority: 'high',
    deadline: '2026-09-15',
    deadlineText: '15.9.2026',
    decisionDate: 'vaihtelee',
    url: 'https://www.paulo.fi/',
    notes: 'Kelpoisuus: Taide ja tiede, suomalainen yhteys\nHakukierrokset: 1 kierros/vuosi\nPäätös: vaihtelee\nVaatimukset: Korkeatasoinen taiteellinen tai tieteellinen työ\nLiitteet: Suunnitelma, CV, näytteet, suositukset\nYhteys: info@paulo.fi',
  },
  {
    id: 'g_hetki_fi25',
    year: 2026,
    funder: 'Tradeka',
    grantName: 'Yhteiskunnalliset hankkeet',
    amount: 0,
    amountText: '10–50 k€',
    status: 'planning',
    project: 'social',
    priority: 'high',
    deadline: '2026-01-31',
    deadlineText: '31.1.2026',
    decisionDate: 'n. 2–3 kk',
    url: 'https://tradeka-yhtio.fi/saatio/',
    notes: 'Erinomainen impact-tuotannoille ja vaikuttamisviestintään.\nKelpoisuus: Yhteisöt, järjestöt, työryhmät; yht.k.vaikuttavuus\nHakukierrokset: Useita teemahakuja/vuosi\nPäätös: n. 2–3 kk\nVaatimukset: Yhteiskunnallinen muutostavoite, yhdenvertaisuus\nLiitteet: Hankesuunnitelma, budjetti, vaikuttavuus, kumppanit\nYhteys: saatio@tradeka.fi',
  },
  {
    id: 'g_hetki_fi26',
    year: 2026,
    funder: 'Saastamoisen Säätiö',
    grantName: 'Apuraha',
    amount: 0,
    amountText: '5–30 k€',
    status: 'planning',
    project: 'personal',
    priority: 'high',
    deadline: '2026-02-28',
    deadlineText: '28.2.2026',
    decisionDate: 'vaihtelee',
    url: 'https://www.saastamoisensaatio.fi/',
    notes: 'Kelpoisuus: Taideammattilaiset, Suomi-yhteys\nHakukierrokset: 1 kierros/vuosi\nPäätös: vaihtelee\nVaatimukset: Korkealaatuinen taiteellinen työ\nLiitteet: Suunnitelma, CV, työnäytteet\nYhteys: info@saastamoisensaatio.fi',
  },
  {
    id: 'g_hetki_fi27',
    year: 2026,
    funder: 'Patricia Seppälän Säätiö',
    grantName: 'Kuvajournalismin apuraha',
    amount: 0,
    amountText: '5–20 k€',
    status: 'planning',
    project: 'social',
    priority: 'high',
    deadline: '2026-01-31',
    deadlineText: '31.1.2026 klo 23.59',
    decisionDate: 'vaihtelee',
    url: 'https://patriciaseppalansaatio.fi/',
    notes: 'Hyvä reittinen valokuvauspohjaiseen dokumenttiin.\nKelpoisuus: Valokuvajournalismi ja siihen liittyvä dok.työ\nHakukierrokset: 1 kierros/vuosi\nPäätös: vaihtelee\nVaatimukset: Laadukas kuva-/dokumenttijournalismi\nLiitteet: Projektisuunnitelma, näytteet, budjetti, CV\nYhteys: info@patriciaseppalansaatio.fi',
  },
  {
    id: 'g_hetki_fi28',
    year: 2026,
    funder: 'Karjalaisen Kulttuurin Edistämissäätiö (KKES)',
    grantName: 'Apuraha',
    amount: 0,
    amountText: '3–15 k€',
    status: 'planning',
    project: 'personal',
    priority: 'high',
    deadline: '2026-11-30',
    deadlineText: '~30.11.2026 (aikataulu tarkentuu)',
    decisionDate: 'vaihtelee',
    url: 'https://www.kkes.fi/',
    notes: 'Kelpoisuus: Karjalaiseen kulttuuriin liittyvä työ\nHakukierrokset: 1 kierros/vuosi\nPäätös: vaihtelee\nVaatimukset: Yhteys karjalaiseen kulttuuriin\nLiitteet: Suunnitelma, CV, näytteet\nYhteys: info@kkes.fi',
  },
  {
    id: 'g_hetki_no01',
    year: 2026,
    funder: 'Nordisk Film & TV Fond',
    grantName: 'Production Support',
    amount: 0,
    amountText: 'Top-financing dok 200–500 k€; fiktio jopa 1 M NOK',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadlineText: 'Jatkuva (rolling)',
    decisionDate: 'n. 6 vk',
    url: 'https://nordiskfilmogtvfond.com/funding/applying-for-funding',
    notes: '2026 alkaen dokumenteilla deadline = 12 vk ennen locked edit.\nKelpoisuus: Pohjoismainen tuotantoyhtiö; jakelusopimus pohjoismainen broadcaster\nHakukierrokset: Jatkuva (rolling)\nPäätös: n. 6 vk\nVaatimukset: Sitoumus pohjoismaiselta broadcasterilta, kansainvälinen levityspotentiaali\nLiitteet: Käsikirjoitus, budjetti, rahoitussuunnitelma, broadcaster-sitoumus, levityssuunnitelma\nYhteys: info@nftvf.com',
  },
  {
    id: 'g_hetki_no02',
    year: 2026,
    funder: 'Nordic Culture Point',
    grantName: 'Mobility Funding',
    amount: 0,
    amountText: 'Matka- ja oleskelukulut, max 14 pv',
    status: 'planning',
    project: 'personal',
    priority: 'international',
    deadline: '2026-02-02',
    deadlineText: '2.2.2026 (1. kierros); 18.8.–18.9.2026 (2. kierros)',
    decisionDate: 'n. 6–8 vk',
    url: 'https://www.nkk.org/en/mobility-funding/',
    notes: 'Hyvä tutkimusmatkoihin, ennakkohaastatteluihin, festivaaleihin.\nKelpoisuus: Pohjoismaiden tai Baltian asukas, ammattitaiteilija/-tekijä\nHakukierrokset: 3 kierrosta/vuosi\nPäätös: n. 6–8 vk\nVaatimukset: Kutsu tai aiekirje vastaanottavalta\nLiitteet: Hakemus, kutsukirje, CV, suunnitelma\nYhteys: kontakt@nkk.org',
  },
  {
    id: 'g_hetki_no03',
    year: 2026,
    funder: 'Nordic Culture Point',
    grantName: 'Project Funding',
    amount: 0,
    amountText: '5–100 k€ (max 50 % budjetista)',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-09-10',
    deadlineText: '10.9.2026',
    decisionDate: 'n. 4 kk',
    url: 'https://www.nkk.org/en/apply-for-funding/',
    notes: 'Vaatii kumppanit muista pohjoismaista.\nKelpoisuus: Vähintään 3 pohjoismaata mukana (tai 2 Pohj. + 1 Balt.)\nHakukierrokset: 2 kierrosta/vuosi\nPäätös: n. 4 kk\nVaatimukset: Pohjoismainen yhteistyö, yhteiskunnallinen relevanssi\nLiitteet: Hankesuunnitelma, kumppanit, budjetti, vaikuttavuus\nYhteys: kontakt@nkk.org',
  },
  {
    id: 'g_hetki_no04',
    year: 2026,
    funder: 'Nordic Culture Fund',
    grantName: 'Project Funding',
    amount: 0,
    amountText: 'n. 10–100 k€',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-09-04',
    deadlineText: '4.9.2026',
    decisionDate: 'n. 4 kk',
    url: 'https://nordiskkulturfond.org/en/funding-programmes/project-funding-for-collaborations-across-the-nordic-region',
    notes: 'Kelpoisuus: Pohjoismainen yhteistyö (väh. 3 maata)\nHakukierrokset: Useita teemahakuja/vuosi\nPäätös: n. 4 kk\nVaatimukset: Pohjoismainen yhteistyö, taiteellinen laatu\nLiitteet: Hankesuunnitelma, kumppanit, budjetti\nYhteys: info@nordiskkulturfond.org',
  },
  {
    id: 'g_hetki_no05',
    year: 2026,
    funder: 'Sørfond (Norjan elokuvainst.)',
    grantName: 'South Film Fund',
    amount: 0,
    amountText: 'n. 1 M NOK (≈ 85 k€)',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-08-12',
    deadlineText: '12.8.2026',
    decisionDate: 'n. 3 kk',
    url: 'https://www.nfi.no/eng/grants/sorfond',
    notes: 'Vaatii norjalaisen yht.tuotantokumppanin.\nKelpoisuus: Norjalainen tuotantoyhtiö yht.tuottaa eteläisen kumppanin kanssa\nHakukierrokset: 1–2 kierrosta/vuosi\nPäätös: n. 3 kk\nVaatimukset: Globaalin etelän ohjaaja, norjalainen yht.tuottaja\nLiitteet: Käsikirjoitus, treatment, budjetti, sopimukset\nYhteys: sorfond@nfi.no',
  },
  {
    id: 'g_hetki_eu01',
    year: 2026,
    funder: 'Creative Europe MEDIA',
    grantName: 'Single Project Development',
    amount: 0,
    amountText: '25–60 k€',
    status: 'planning',
    project: 'development',
    priority: 'international',
    deadline: '2026-02-23',
    deadlineText: '23.2.2026',
    decisionDate: 'n. 4–5 kk',
    url: 'https://creativeeurope.fi/',
    notes: 'Kaila ry / Creative Europe Desk Finland antaa neuvontaa.\nKelpoisuus: Eurooppalainen riippumaton tuotantoyhtiö (väh. 12 kk vanha)\nHakukierrokset: 1–2 kierrosta/vuosi\nPäätös: n. 4–5 kk\nVaatimukset: Yhden projektin kehitysrahoitus, kv. levityspotentiaali\nLiitteet: Synopsis, treatment, budjetti, yhtiön tausta, kv-strategia\nYhteys: media@kaila.eu (FI: Creative Europe Desk)',
  },
  {
    id: 'g_hetki_eu02',
    year: 2026,
    funder: 'Creative Europe MEDIA',
    grantName: 'European Slate Development',
    amount: 0,
    amountText: '510 k€ slate (3 proj.); 660 k€ (4 proj.); 810 k€ (5 proj.)',
    status: 'planning',
    project: 'development',
    priority: 'international',
    deadline: '2026-05-07',
    deadlineText: '7.5.2026',
    decisionDate: 'Syksy 2026',
    url: 'https://a-mcc.eu/en/funding/calls/european-slate-development-crea-media-2026-devslate/',
    notes: 'Erittäin kilpailtu, mutta merkittävä rahoituskanava.\nKelpoisuus: Riippumaton eurooppalainen tuotantoyhtiö, näyttöä\nHakukierrokset: 1 kierros/vuosi\nPäätös: Syksy 2026\nVaatimukset: Slate-strategia, yhtiön kv. kasvu, projektien yhteismitalliset tavoitteet\nLiitteet: Slate-suunnitelma, projektien treatmentit, budjetti, yhtiön talous\nYhteys: media@kaila.eu',
  },
  {
    id: 'g_hetki_eu03',
    year: 2026,
    funder: 'Creative Europe MEDIA',
    grantName: 'Mini-Slate Development',
    amount: 0,
    amountText: '140 k€ / 2 proj.',
    status: 'planning',
    project: 'development',
    priority: 'international',
    deadline: '2026-09-17',
    deadlineText: '17.9.2026',
    decisionDate: 'n. 5 kk',
    url: 'https://creativeeurope.in.ua/en/call/crea_media_2026_devminislate',
    notes: 'Kelpoisuus: Pieni/keskikok. riippumaton eur. tuotantoyhtiö\nHakukierrokset: 1 kierros/vuosi\nPäätös: n. 5 kk\nVaatimukset: Kasvavalle yhtiölle reitti slate-kehitykseen\nLiitteet: Mini-slate, projektien treatmentit, budjetti\nYhteys: media@kaila.eu',
  },
  {
    id: 'g_hetki_eu04',
    year: 2026,
    funder: 'Creative Europe MEDIA',
    grantName: 'European Co-Development',
    amount: 0,
    amountText: '60–100 k€',
    status: 'planning',
    project: 'development',
    priority: 'international',
    deadline: '2026-05-07',
    deadlineText: '7.5.2026',
    decisionDate: 'Syksy 2026',
    url: 'https://a-mcc.eu/en/funding/calls/european-co-development-crea-media-2026-codev/',
    notes: 'Kelpoisuus: Kaksi eri maissa toimivaa eur. tuottajaa; co-dev. sopimus\nHakukierrokset: 1 kierros/vuosi\nPäätös: Syksy 2026\nVaatimukset: Yhden yht.tuotantoprojektin kehitysrahoitus\nLiitteet: Co-dev. sopimus, käsikirjoitus, budjetti, kv-strategia\nYhteys: media@kaila.eu',
  },
  {
    id: 'g_hetki_eu05',
    year: 2026,
    funder: 'Creative Europe MEDIA',
    grantName: 'TV and Online Content (Documentary)',
    amount: 0,
    amountText: '300–500 k€',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-05-07',
    deadlineText: '7.5.2026',
    decisionDate: 'n. 5 kk',
    url: 'https://www.euro-access.eu/en/calls/2400/TV-and-online-content-Documentary-projects-2nd-cut-off-date',
    notes: 'Kelpoisuus: Vaatii ≥ 3 broadcasterin / VOD-alustan sitoumusta eri EU-maista\nHakukierrokset: 2 kierrosta/vuosi\nPäätös: n. 5 kk\nVaatimukset: Pan-eurooppalainen yht.tuotantorakenne, sitoumukset olemassa\nLiitteet: Käsikirjoitus, paketit, broadcaster-sopimukset, budjetti\nYhteys: media@kaila.eu',
  },
  {
    id: 'g_hetki_eu06',
    year: 2026,
    funder: 'Creative Europe MEDIA',
    grantName: 'TV and Online Content (Fiction)',
    amount: 0,
    amountText: '500 k€ – 2 M€',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-05-07',
    deadlineText: '7.5.2026 (cut-off)',
    decisionDate: 'n. 5 kk',
    url: 'https://culture.ec.europa.eu/creative-europe',
    notes: 'Kelpoisuus: Vaatii ≥ 3 broadcasteria eri maista, korkea kv. potentiaali\nHakukierrokset: 2 kierrosta/vuosi\nPäätös: n. 5 kk\nVaatimukset: Pan-eur. sitoumukset, vahva kv. levityspotentiaali\nLiitteet: Käsikirjoitus, paketit, broadcaster-sopimukset, budjetti\nYhteys: media@kaila.eu',
  },
  {
    id: 'g_hetki_eu07',
    year: 2026,
    funder: 'Eurimages',
    grantName: 'Co-production Support',
    amount: 0,
    amountText: 'n. 200–500 k€',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-01-09',
    deadlineText: '9.1.2026 klo 12:00 CET (seuraava avautuu pian)',
    decisionDate: 'n. 3 kk',
    url: 'https://www.coe.int/en/web/eurimages/coproduction',
    notes: 'Uudet säännöt voimassa 1.1.2026 alkaen.\nKelpoisuus: Yht.tuotanto väh. 2 Eurimages-jäsenmaan tuottajan kesken\nHakukierrokset: 2–4 kierrosta/vuosi\nPäätös: n. 3 kk\nVaatimukset: Yht.tuotantosopimus, rahoitus ≥ 50 %, sopimukset levityksestä\nLiitteet: Sopimukset, käsikirjoitus, budjetti, rahoitussuunnitelma, kestävyyssuunnitelma\nYhteys: eurimages@coe.int',
  },
  {
    id: 'g_hetki_eu08',
    year: 2026,
    funder: 'Eurimages',
    grantName: 'Series Co-production',
    amount: 0,
    amountText: 'n. 200–500 k€',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-04-14',
    deadlineText: '14.4.2026',
    decisionDate: 'n. 3 kk',
    url: 'https://spainaudiovisualhub.digital.gob.es/en/actualidad/eurimages---programme-for-series-co---productions--support-for-s',
    notes: 'Kelpoisuus: Sarja, yht.tuotanto väh. 2 Eurimages-maan tuottajan kesken\nHakukierrokset: 1–2 kierrosta/vuosi\nPäätös: n. 3 kk\nVaatimukset: Sarjamuotoinen yht.tuotanto\nLiitteet: Sopimukset, käsikirjoitus, budjetti, paketit\nYhteys: eurimages@coe.int',
  },
  {
    id: 'g_hetki_eu09',
    year: 2026,
    funder: 'Creative Europe CULTURE',
    grantName: 'Cooperation Projects',
    amount: 0,
    amountText: '200 k€ – 2 M€ (pienet/keskik./isot)',
    status: 'planning',
    project: 'social',
    priority: 'international',
    deadline: '2026-05-05',
    deadlineText: '5.5.2026',
    decisionDate: 'n. 5 kk',
    url: 'https://culture.ec.europa.eu/creative-europe',
    notes: 'Sopiva impact-/yht.k. taideprojekteille.\nKelpoisuus: Kulttuurialan organisaatio, eur. kumppanit\nHakukierrokset: 1 kierros/vuosi\nPäätös: n. 5 kk\nVaatimukset: Eurooppalainen kulttuuriyhteistyö, eu-arvot\nLiitteet: Hankesuunnitelma, kumppanit, budjetti, vaikuttavuus\nYhteys: culture@kaila.eu',
  },
  {
    id: 'g_hetki_eu10',
    year: 2026,
    funder: 'EU CERV',
    grantName: 'Citizens, Equality, Rights and Values',
    amount: 0,
    amountText: '100 k€ – 1 M€',
    status: 'planning',
    project: 'social',
    priority: 'international',
    deadline: '2026-04-28',
    deadlineText: '28.4.2026',
    decisionDate: 'n. 4–6 kk',
    url: 'https://hadea.ec.europa.eu/programmes/citizens-equality-rights-and-values-programme_en',
    notes: 'Useimmiten edellytetään yhteisö-/järjestöhakijaa.\nKelpoisuus: Voittoa tavoittelematon organisaatio; eur. kumppaniverkosto\nHakukierrokset: Useita teemahakuja/vuosi\nPäätös: n. 4–6 kk\nVaatimukset: Demokratia, yhdenvertaisuus, oikeudet; eu-arvot\nLiitteet: Hankesuunnitelma, kumppanit, budjetti, vaikuttavuus\nYhteys: EACEA-CERV@ec.europa.eu',
  },
  {
    id: 'g_hetki_kv01',
    year: 2026,
    funder: 'IDFA Bertha Fund',
    grantName: 'Classic (Globaali etelä)',
    amount: 0,
    amountText: 'n. 25 k€',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-04-01',
    deadlineText: '1.4.2026',
    decisionDate: 'n. 4 kk',
    url: 'https://professionals.idfa.nl/training-funding/funding/about-the-idfa-bertha-fund/',
    notes: 'Ei sovi suoraan suomalaiselle hakijalle, mutta yht.tuottajana mahdollinen.\nKelpoisuus: Ohjaaja/tuottaja IBF Classic -maista (ei Suomi)\nHakukierrokset: 1 kierros/vuosi\nPäätös: n. 4 kk\nVaatimukset: Tekijä kohdemaista; taiteellinen visio\nLiitteet: Treatment, käsikirjoitus, näytteet, budjetti, rahoitussuunnitelma\nYhteys: ibf@idfa.nl',
  },
  {
    id: 'g_hetki_kv02',
    year: 2026,
    funder: 'IDFA Bertha Fund',
    grantName: 'Europe',
    amount: 0,
    amountText: 'n. 25 k€',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-04-01',
    deadlineText: '1.4.2026',
    decisionDate: 'n. 4 kk',
    url: 'https://professionals.idfa.nl/training-funding/funding/',
    notes: 'Sopii vain spesifeissä tapauksissa.\nKelpoisuus: Eurooppalainen ohjaaja vähemmistö-/aliedustetuista taustoista\nHakukierrokset: 1 kierros/vuosi\nPäätös: n. 4 kk\nVaatimukset: Vähemmistö-/aliedustettu tekijä\nLiitteet: Treatment, näyte, budjetti, rahoitussuunnitelma\nYhteys: ibf@idfa.nl',
  },
  {
    id: 'g_hetki_kv03',
    year: 2026,
    funder: 'Sundance Institute Documentary Fund',
    grantName: 'Tuotantotuki',
    amount: 0,
    amountText: '10–50 k€',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-06-15',
    deadlineText: '18.5.–15.6.2026',
    decisionDate: 'Joulukuu 2026',
    url: 'https://www.sundance.org/documentary-fund/',
    notes: 'Globaalisti haettavissa; erittäin kilpailtu.\nKelpoisuus: Itsenäinen tekijä; budjetti < 1,2 M$\nHakukierrokset: 1 kierros/vuosi\nPäätös: Joulukuu 2026\nVaatimukset: Taiteellinen visio, journ. tarkkuus, kulttuurinen relevanssi\nLiitteet: Synopsis, treatment, näytemateriaali, budjetti, rahoitussuunnitelma\nYhteys: docfund@sundance.org',
  },
  {
    id: 'g_hetki_kv04',
    year: 2026,
    funder: 'Sundance Sandbox Fund (Science Storytelling)',
    grantName: 'Tuotantotuki',
    amount: 0,
    amountText: '25–100 k€',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-04-13',
    deadlineText: '13.4.2026 klo 23 ET',
    decisionDate: 'Loppukesä 2026',
    url: 'https://www.sundance.org/sandbox-fund/',
    notes: 'Sopii tiedettä käsittelevälle dokumenttiprojektille.\nKelpoisuus: Itsenäinen tekijä; tieteen ja taiteen risteys\nHakukierrokset: 1 kierros/vuosi\nPäätös: Loppukesä 2026\nVaatimukset: Tieteellisen ja taiteellisen tarinankerronnan yhdistäminen\nLiitteet: Treatment, näyte, budjetti, tieteellinen neuvonantaja\nYhteys: sandbox@sundance.org',
  },
  {
    id: 'g_hetki_kv05',
    year: 2026,
    funder: 'Doc Society',
    grantName: 'Climate Story Fund',
    amount: 0,
    amountText: '50–125 k$',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-03-10',
    deadlineText: '~maaliskuu 2026 (aikataulu tarkentuu)',
    decisionDate: 'n. 3 kk',
    url: 'https://climatestoryunit.org/apply/',
    notes: 'Erinomainen reitti ilmastoteemaiselle dokumenttihankkeelle.\nKelpoisuus: Globaalisti haettavissa; ilmastoaihe; vahva impact-strategia\nHakukierrokset: Useita avauksia/vuosi (rolling)\nPäätös: n. 3 kk\nVaatimukset: Ilmastokriisi keskeisenä teemana; impact-suunnitelma\nLiitteet: Treatment, impact-suunnitelma, budjetti, näyte\nYhteys: climate@docsociety.org',
  },
  {
    id: 'g_hetki_kv06',
    year: 2026,
    funder: 'Ford Foundation',
    grantName: 'JustFilms',
    amount: 0,
    amountText: '50–500 k$',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadlineText: 'Jatkuva (LOI)',
    decisionDate: 'vaihtelee',
    url: 'https://www.fordfoundation.org/work/our-grants/justfilms/',
    notes: 'Vahva impact-fokus. Kontaktoi etukäteen.\nKelpoisuus: Yhteiskunnallista oikeudenmukaisuutta käsittelevät projektit\nHakukierrokset: Pyynnöstä (kutsupohjainen + LOI)\nPäätös: vaihtelee\nVaatimukset: Yht.k. oikeudenmukaisuus, vahva impact\nLiitteet: LOI, treatment, budjetti, impact-suunnitelma\nYhteys: info@fordfoundation.org',
  },
  {
    id: 'g_hetki_kv07',
    year: 2026,
    funder: 'Bertha Foundation',
    grantName: 'Doc Society & Activist Filmmakers',
    amount: 0,
    amountText: 'n. 25–100 k$',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadlineText: 'Jatkuva (LOI)',
    decisionDate: 'vaihtelee',
    url: 'https://berthafoundation.org/',
    notes: 'Kelpoisuus: Aktivistinen dokumenttielokuva, vahva muutosvoima\nHakukierrokset: Pyynnöstä (LOI)\nPäätös: vaihtelee\nVaatimukset: Aktivismi ja yht.k. muutos keskiössä\nLiitteet: LOI, treatment, kumppanit, impact\nYhteys: info@berthafoundation.org',
  },
  {
    id: 'g_hetki_kv08',
    year: 2026,
    funder: 'Chicken & Egg Pictures',
    grantName: 'Tuotantotuki',
    amount: 0,
    amountText: '5–50 k$',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-02-04',
    deadlineText: '4.2.2026',
    decisionDate: 'n. 4 kk',
    url: 'https://chickeneggpics.org/',
    notes: 'Kelpoisuus: Naiset ja genderqueer dokumenttiohjaajat\nHakukierrokset: 1–2 kierrosta/vuosi\nPäätös: n. 4 kk\nVaatimukset: Naisten/queerien tekijöiden uran tukeminen\nLiitteet: Treatment, näyte, budjetti, CV\nYhteys: info@chickeneggpics.org',
  },
  {
    id: 'g_hetki_kv09',
    year: 2026,
    funder: 'Catapult Film Fund',
    grantName: 'Kehittäminen',
    amount: 0,
    amountText: 'max 20 k$',
    status: 'planning',
    project: 'development',
    priority: 'international',
    deadline: '2026-04-20',
    deadlineText: '20.4.2026',
    decisionDate: 'n. 3 kk',
    url: 'https://catapultfilmfund.org/',
    notes: 'Hyvä varhaisen vaiheen dokumenttiin.\nKelpoisuus: Globaalisti haettavissa, varhainen vaihe\nHakukierrokset: 2 kierrosta/vuosi\nPäätös: n. 3 kk\nVaatimukset: Vahvat näyttömateriaalit, selkeä taiteellinen visio\nLiitteet: Treatment, näytemateriaali, budjetti\nYhteys: info@catapultfilmfund.org',
  },
  {
    id: 'g_hetki_kv10',
    year: 2026,
    funder: 'Whickers Funding Awards',
    grantName: 'Funding Award',
    amount: 0,
    amountText: 'Pääpalkinto £80 k; pitching £10 k',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-01-30',
    deadlineText: '30.1.2026',
    decisionDate: 'Sheffield DocFest (kesäkuu)',
    url: 'https://whickersworld.com/funding-awards/',
    notes: 'Sheffield DocFestin yhteydessä.\nKelpoisuus: Esikoispitkä dokumentti\nHakukierrokset: 1 kierros/vuosi\nPäätös: Sheffield DocFest (kesäkuu)\nVaatimukset: Esikoisohjaaja, vahva visio\nLiitteet: Treatment, näyte, budjetti, CV\nYhteys: info@whickerworld.com',
  },
  {
    id: 'g_hetki_kv11',
    year: 2026,
    funder: 'World Cinema Fund (Berlinale / HKW)',
    grantName: 'Tuotantotuki',
    amount: 0,
    amountText: 'n. 25–100 k€',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-03-04',
    deadlineText: '4.3.2026',
    decisionDate: 'n. 3 kk',
    url: 'https://www.berlinale.de/en/world-cinema-fund/',
    notes: 'Sopiva suomalaiselle yht.tuottajalle ei-eur. ohjaajan projektissa.\nKelpoisuus: Ensisijaisesti Aasia, Afrikka, L-Amerikka, M-Itä; eur. yht.tuottaja\nHakukierrokset: 2 kierrosta/vuosi\nPäätös: n. 3 kk\nVaatimukset: Globaalin etelän tekijä, eur. tuotantokumppani\nLiitteet: Käsikirjoitus, paketit, budjetti, sopimukset\nYhteys: wcf@berlinale.de',
  },
  {
    id: 'g_hetki_kv12',
    year: 2026,
    funder: 'ARTE',
    grantName: 'Co-production / Pre-buy',
    amount: 0,
    amountText: 'Vaihtelee — kohdekohtainen',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadlineText: 'Jatkuva (rolling)',
    decisionDate: 'vaihtelee',
    url: 'https://www.arte.tv/sites/en/corporate/coproductions/',
    notes: 'ARTE on yksi vahvimpia eur. dokumenttibroadcastereita.\nKelpoisuus: Eur. tuotantoyhtiö, ARTE:n ohjelmaprofiiliin sopiva\nHakukierrokset: Jatkuva tarjousmenettely\nPäätös: vaihtelee\nVaatimukset: Vahva taiteellinen näkemys, kv. relevanssi\nLiitteet: Treatment, näyte, budjetti, rahoitussuunnitelma\nYhteys: Tarkista ARTE.tv producers',
  },
  {
    id: 'g_hetki_kv13',
    year: 2026,
    funder: 'ITVS (PBS)',
    grantName: 'International Call',
    amount: 0,
    amountText: '25–100 k$',
    status: 'planning',
    project: 'production',
    priority: 'international',
    deadline: '2026-03-15',
    deadlineText: '~maaliskuu 2026 (aikataulu tarkentuu)',
    decisionDate: 'n. 6 kk',
    url: 'https://itvs.org/funding',
    notes: 'Vaatii käytännössä US-yhteistuottajan.\nKelpoisuus: Ei-US-ohjaaja, yhdysvaltalainen yht.tuottaja\nHakukierrokset: 1 kierros/vuosi\nPäätös: n. 6 kk\nVaatimukset: Yhdysvaltalaisen yleisön kannalta relevantti\nLiitteet: Treatment, näyte, budjetti, rahoitus, US-yht.tuottaja\nYhteys: open.call@itvs.org',
  },
  {
    id: 'g_hetki_kv14',
    year: 2026,
    funder: 'Hot Docs Forum & Market',
    grantName: 'Pitching',
    amount: 0,
    amountText: 'Pitching → broadcaster-/rahoittajatapaamiset',
    status: 'planning',
    project: 'distribution',
    priority: 'international',
    deadline: '2026-11-26',
    deadlineText: '~marraskuu 2026 seur. kierros (aikataulu tarkentuu)',
    decisionDate: 'n. 2 kk',
    url: 'https://hotdocs.ca/industry/forum',
    notes: 'Avain reittinen kv. yht.tuotantoihin ja rahoitukseen.\nKelpoisuus: Hyvä projekti pitchausvaiheessa\nHakukierrokset: 1 kierros/vuosi\nPäätös: n. 2 kk\nVaatimukset: Pitchausvalmis projekti, käsikirjoitus, näyte\nLiitteet: Pitch-paketti, näyte, sizzle, budjetti\nYhteys: forum@hotdocs.ca',
  },
  {
    id: 'g_hetki_kv15',
    year: 2026,
    funder: 'CPH:DOX Forum (CPH:Conference)',
    grantName: 'Forum / Pitching',
    amount: 0,
    amountText: 'Pitching → rahoittajat',
    status: 'planning',
    project: 'distribution',
    priority: 'international',
    deadline: '2026-11-05',
    deadlineText: '~marraskuun alku 2026 (aikataulu tarkentuu)',
    decisionDate: 'n. 2 kk',
    url: 'https://cphdox.dk/industry',
    notes: 'Kannattaa yhdistää SES:n development-tuella tehtyyn projektiin.\nKelpoisuus: Eur. dokumenttiprojekti\nHakukierrokset: 1 kierros/vuosi\nPäätös: n. 2 kk\nVaatimukset: Pitching-valmis, eur. profiili\nLiitteet: Pitch-paketti, näyte, budjetti\nYhteys: forum@cphdox.dk',
  },
];

export const HETKI_GRANTS_DEFAULT: Grant[] = [...HETKI_GRANTS_2026];

export const HETKI_GRANTS_SETTINGS: GrantsSettings = {
  yearTargets: { '2026': 150000, '2027': 150000 },
  defaultYear: 2026,
};
