// Juhlatoimikunta — Sirpan 70v syntymäpäiväjuhlien järjestelytiimi
// Erillinen ja irrallinen työtila Momentumissa

import { OrgTeam, OrgTeamMember } from './team-shared';
import type { CommsPlan } from './comms-plan-shared';
import type { YearPhase } from './yearwheel-shared';

export const DEFAULT_JUHLATOIMIKUNTA_TEAMS: OrgTeam[] = [
  {
    id: 'juhlatoimikunta',
    name: 'Juhlatoimikunta',
    color: '#9b7cf6',
    icon: '★',
    description: 'Sirpan 70-vuotisjuhlien järjestelytiimi.',
    leadId: 'sonja',
  },
];

export const DEFAULT_JUHLATOIMIKUNTA_TEAM_MEMBERS: OrgTeamMember[] = [
  {
    id: 'sonja',
    name: 'Sonja Baer',
    role: 'Juhlatoimikunnan vetäjä',
    teamId: 'juhlatoimikunta',
    type: 'permanent',
    avatar: 'S',
    email: 'baerhelle@gmail.com',
    linkedUserEmails: ['baerhelle@gmail.com'],
    responsibilities: [],
    channels: [],
  },
  {
    id: 'raisa',
    name: 'Raisa Baer',
    role: 'Jäsen',
    teamId: 'juhlatoimikunta',
    type: 'permanent',
    avatar: 'R',
    responsibilities: [],
    channels: [],
  },
  {
    id: 'elina',
    name: 'Elina Savo',
    role: 'Jäsen',
    teamId: 'juhlatoimikunta',
    type: 'permanent',
    avatar: 'E',
    responsibilities: [],
    channels: [],
  },
  {
    id: 'anton',
    name: 'Anton Baer',
    role: 'Jäsen',
    teamId: 'juhlatoimikunta',
    type: 'permanent',
    avatar: 'A',
    email: 'anton@hetkicompany.com',
    linkedUserEmails: ['anton@hetkicompany.com', 'anton.baer@gmail.com'],
    responsibilities: [],
    channels: [],
  },
];

export const DEFAULT_JUHLATOIMIKUNTA_YEARWHEEL: YearPhase[] = [
  {
    id: 'jtk1',
    name: 'Suunnittelu ja vastuunjako',
    category: 'planning',
    team: 'hallinto',
    startMonth: 4, endMonth: 4,
    startDate: '2026-04-12', endDate: '2026-04-15',
    color: '#056b9f', icon: '◇',
    desc: 'Juhlasuunnitelman viimeistely, vastuunjako tiimin kesken, budjetin lukitseminen ja hankintalistojen laatiminen.',
    tasks: [
      { id: 'jt1', text: 'Budjetti ja kuluerittely valmiiksi', month: 4, week: 16, done: false, owner: 'Sonja Baer' },
      { id: 'jt2', text: 'Tilavarauksen varmistus (Tyttöjen talo)', month: 4, week: 16, done: false, owner: 'Sonja Baer' },
      { id: 'jt3', text: 'Ohjelman runko valmiiksi', month: 4, week: 16, done: false, owner: 'Anton Baer' },
      { id: 'jt4', text: 'Vastuunjako: kuka hoitaa mitäkin', month: 4, week: 16, done: false, owner: 'Sonja Baer' },
      { id: 'jt5', text: 'Vieraslistan läpikäynti ja päivitys', month: 4, week: 16, done: false, owner: 'Raisa Baer' },
    ],
  },
  {
    id: 'jtk2',
    name: 'Hankinnat ja tilaukset',
    category: 'production',
    team: 'tuotanto',
    startMonth: 4, endMonth: 4,
    startDate: '2026-04-16', endDate: '2026-04-20',
    color: '#f1b434', icon: '▣',
    desc: 'Ruoka- ja juomatilaukset, koristeiden hankinta, musiikki- ja tekniikkajärjestelyt.',
    tasks: [
      { id: 'jt6', text: 'Kakun tilaus', month: 4, week: 16, done: false, owner: 'Elina Savo' },
      { id: 'jt7', text: 'Ruokatarjoilujen suunnittelu ja tilaukset', month: 4, week: 17, done: false, owner: 'Raisa Baer' },
      { id: 'jt8', text: 'Juomien hankinta (viinit, kuohuviini, alkoholittomat)', month: 4, week: 17, done: false, owner: 'Anton Baer' },
      { id: 'jt9', text: 'Koristeet ja somistustarvikkeet', month: 4, week: 17, done: false, owner: 'Elina Savo' },
      { id: 'jt10', text: 'Musiikki-/äänentoistolaitteet (soittolista tai live)', month: 4, week: 17, done: false, owner: 'Anton Baer' },
      { id: 'jt11', text: 'Kukat ja kukkajärjestelyt', month: 4, week: 17, done: false, owner: 'Sonja Baer' },
      { id: 'jt12', text: 'Astiat, lautasliinat, pöytäliinat', month: 4, week: 17, done: false, owner: 'Raisa Baer' },
    ],
  },
  {
    id: 'jtk3',
    name: 'Viimeistely ja valmistautuminen',
    category: 'production',
    team: 'tuotanto',
    startMonth: 4, endMonth: 4,
    startDate: '2026-04-21', endDate: '2026-04-24',
    color: '#e45c81', icon: '◉',
    desc: 'Kutsujen viimeistely, aikataulun lukitseminen, ruokavalmistelut ja viime hetken tarkistukset.',
    tasks: [
      { id: 'jt13', text: 'Lopullinen vieraslista ja ilmoittautumisten tarkistus', month: 4, week: 17, done: false, owner: 'Raisa Baer' },
      { id: 'jt14', text: 'Ohjelma-aikataulu lukittu ja jaettu tiimille', month: 4, week: 17, done: false, owner: 'Anton Baer' },
      { id: 'jt15', text: 'Muistutusviesti vieraille (WhatsApp/sähköposti)', month: 4, week: 17, done: false, owner: 'Sonja Baer' },
      { id: 'jt16', text: 'Ennakkoon valmistettavat ruoat (pe-iltana)', month: 4, week: 17, done: false, owner: 'Raisa Baer' },
      { id: 'jt17', text: 'Kuljetussuunnitelma: kuka tuo mitäkin Tyttöjen talolle', month: 4, week: 17, done: false, owner: 'Anton Baer' },
      { id: 'jt18', text: 'Puheenvuorot: kuka pitää puheen/maljan', month: 4, week: 17, done: false, owner: 'Sonja Baer' },
    ],
  },
  {
    id: 'jtk4',
    name: 'Juhlapäivä — la 25.4.2026',
    category: 'execution',
    team: 'tuotanto',
    isFestival: true,
    startMonth: 4, endMonth: 4,
    startDate: '2026-04-25', endDate: '2026-04-25',
    color: '#ef6b6b', icon: '★',
    desc: 'Sirpan 70-vuotisjuhlat Tyttöjen talolla (Hämeentie 13 A). Valmistelu klo 10, juhlat klo 15–24.',
    tasks: [
      { id: 'jt19', text: '10:00 Saapuminen ja tilan valmistelu', month: 4, week: 17, done: false, owner: 'Kaikki' },
      { id: 'jt20', text: '11:00 Somistus ja koristelu', month: 4, week: 17, done: false, owner: 'Elina Savo' },
      { id: 'jt21', text: '12:00 Ruokien esivalmistelu ja esillepano', month: 4, week: 17, done: false, owner: 'Raisa Baer' },
      { id: 'jt22', text: '14:00 Viimeiset tarkistukset, musiikki päälle', month: 4, week: 17, done: false, owner: 'Anton Baer' },
      { id: 'jt23', text: '15:00 Vieraiden vastaanotto', month: 4, week: 17, done: false, owner: 'Sonja Baer' },
      { id: 'jt24', text: 'Juhlat: ohjelma, puheet, ruokailu, musiikki', month: 4, week: 17, done: false, owner: 'Kaikki' },
      { id: 'jt25', text: '23:00–24:00 Päättäminen ja ensimmäinen siivous', month: 4, week: 17, done: false, owner: 'Kaikki' },
    ],
  },
  {
    id: 'jtk5',
    name: 'Purku ja palautukset',
    category: 'reflection',
    team: 'hallinto',
    startMonth: 4, endMonth: 5,
    startDate: '2026-04-26', endDate: '2026-05-02',
    color: '#2a8a86', icon: '○',
    desc: 'Tilan siivous, lainattujen tavaroiden palautus, laskujen maksu ja kiitosviestit vieraille.',
    tasks: [
      { id: 'jt26', text: 'su 26.4: Tilan loppusiivous ja avainten palautus', month: 4, week: 18, done: false, owner: 'Anton Baer' },
      { id: 'jt27', text: 'ma 27.4: Lainatavarat ja vuokratavarat palautettu', month: 4, week: 18, done: false, owner: 'Elina Savo' },
      { id: 'jt28', text: 'ti 28.4: Kiitosviesti vieraille (WhatsApp + sähköposti)', month: 4, week: 18, done: false, owner: 'Sonja Baer' },
      { id: 'jt29', text: 'ke 29.4: Valokuvien jako vieraille', month: 4, week: 18, done: false, owner: 'Anton Baer' },
      { id: 'jt30', text: 'to 30.4: Laskujen tarkistus ja maksu', month: 4, week: 18, done: false, owner: 'Sonja Baer' },
      { id: 'jt31', text: 'la 2.5: Kaikki palautukset valmiit', month: 5, week: 18, done: false, owner: 'Kaikki' },
    ],
  },
];

export const DEFAULT_JUHLATOIMIKUNTA_COMMS_PLAN: CommsPlan = {
  id: 'juhlatoimikunta-2026-commsplan',
  year: 2026,
  festivalName: 'Sirpan 70v juhlat',
  festivalDates: '25.4.2026',
  summary: 'Sirpan 70-vuotissyntymäpäiväjuhlat järjestetään lauantaina 25.4.2026 Tyttöjen talolla Kalliossa (Hämeentie 13 A, 00530 Helsinki).',
  mission: 'Järjestää Sirpalle ikimuistoiset ja lämminhenkiset 70-vuotisjuhlat.',
  visitorGoal: 0,
  visitorBaseline: 0,
  volunteerGoal: 0,
  volunteerBaseline: 0,
  responsibleMemberId: 'sonja',
  responsibleTeamId: 'juhlatoimikunta',
  activeFrom: '',
  visualIdentityDeadline: '',
  kickoffNote: '',
  strategicMoves: [],
  kpis: [],
  audienceMix: [],
  brandPillars: [],
  milestones: [],
  monthTargets: [],
  phases: [],
  campaigns: [],
  channelMatrix: [],
  contentPillars: [],
  channels: ['WhatsApp', 'Sähköposti'],
  updatedAt: 0,
};
